name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always
  DISCORD_CLIENT_ID: ${{ secrets.DISCORD_CLIENT_ID }}

jobs:
  Ubuntu:
    runs-on: 'ubuntu-latest'
    steps:
    - uses: actions/checkout@v4
    - name: Install Deps
      run: sudo apt-get install g++ pkg-config libx11-dev libasound2-dev libudev-dev libxkbcommon-x11-0
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
  Windows:
    runs-on: 'windows-latest'
    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: cargo build --verbose
      - name: Run tests
        run: cargo test --verbose
  macOS:
    runs-on: 'macos-latest'
    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: cargo build --verbose
      - name: Run tests
        run: cargo test --verbose